mode = "light"

accent = "#805f36"
selection = "#c0b4ab"
muted = "#7f7974"

background = "#f5e4d8"
dark_background = "#b8aba2"
darker_background = "#7b726c"
lighter_background = "#f6e7dc"

foreground = "#3a1911"
dark_foreground = "#2c130d"
light_foreground = "#583c35"
bright_foreground = "#6b534d"

red = "#562b00"
yellow = "#7b5521"
orange = "#6f4b26"
green = "#653e00"
cyan = "#875c26"
blue = "#805f36"
magenta = "#563819"
brown = "#432d17"

bright_red = "#7c4b14"
bright_yellow = "#a27832"
bright_green = "#8b5f0f"
bright_cyan = "#af7f36"
bright_blue = "#a7824b"
bright_magenta = "#7b582f"
